version: '3.7'

services:

  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "pgdata:/var/lib/postgresql/data/pgdata"

  pgadmin:
    image: dpage/pgadmin4:4.10
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: info@michaelwellner.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    volumes:
      - "pgadmin:/var/lib/pgadmin"

  jupyter:
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    restart: always
    ports:
      - 8888:8888
    volumes:
      - "jupyterdata:/home/jovyan/work"


volumes:
  pgdata:
  pgadmin: 
  jupyterdata: